name: New Feature
description: 새로운 기능 추가 논의🪄
title: "[New Feature]"
labels: ["discuss"]
body: 
  - type: textarea
    id: feature-summary
    attributes:
      label: 기능 요약
      description: 고안한 기능에 대한 요약
      placeholder: ex) 운동 시작 시간을 자동으로 채워주는 기능
    validations:
      required: true
  
  - type: textarea
    id: feature-background
    attributes:
      label: 고안 배경
      description: 해당 기능이 필요한 이유
      placeholder: ex) 운동 시작 버튼을 누를때가 운동 시작 시간인 경우가 많아서 매번 누르기 귀찮다.
    validations:
      requried: true

  - type: textarea
    id: feature-flow
    attributes:
      label: 기능 상세 플로우
      description: 해당 기능에 대한 실행 경로 및 세부적인 실행 사항
      placeholder: |
              ex)
              1. 운동 추가버튼 클릭
              2-1. 운동 추가 다이얼로그 띄움
              2-2. 운동 추가 다이얼로그의 시작 시간에 운동추가 버튼을 클릭한 시간을 자동으로 채움(수정가능)
    validations:
      requried: true
    
  - type: textarea
    id: feature-image
    attributes:
      label: 예상 결과
      description: 해당 기능을 추가했을 때 기존 기능과 비교 (이미지 권장)    
    validations:
      requried: true
    





